disabled_rules:
  - line_length
  - nesting
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - file_header
  - first_where
  - number_separator
  - object_literal
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

excluded:
  - Pods
  - Tests

attributes:
  always_on_same_line:
    - '@IBAction'
    - '@NSManaged'
    - '@nonobjc'
    - '@objc'

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  FormValidatorSwift
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} ustwo Fampany Ltd\. All rights reserved\.
                    \/\/

line_length: 110
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 40 # warning
  - 60 # error
variable_name_min_length:
  - 3 # warning
  - 2 # error
vertical_whitespace:
  max_empty_lines: 2
