disabled_rules:
  - line_length
  - nesting
  - trailing_whitespace
  - vertical_whitespace
opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - number_separator
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline

excluded:
  - Pods
  - Tests

attributes:
  always_on_same_line:
    - '@IBAction'
    - '@NSManaged'
    - '@nonobjc'
    - '@objc'
line_length: 110
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 40 # warning
  - 60 # error
variable_name_min_length:
  - 3 # warning
  - 2 # error
